create table Flights
(
    id                bigint generated by default as identity,
    flightNumber      varchar(100) not null,
    departureDate     date         not null,
    `time`            Time         not null,
    origin            varchar(200) not null,
    destination       varchar(200) not null,
    estFlightDuration Time         not null,
    maxNumSeats       integer      not null,
    primary key (id)
);

create table Users
(
    id         bigint generated by default as identity,
    login      varchar(200) not null,
    `password` varchar(200) not null,
    firstName  varchar(200) not null,
    lastName   varchar(200) not null,
    birthDate  date         not null,
    gender     varchar(100) not null,
    primary key (id)
);

create table Passengers
(
    id           bigint generated by default as identity,
    firstName    varchar(200) not null,
    lastName     varchar(200) not null,
    passportData varchar(200) not null,
    birthDate    date         not null,
    gender       varchar(100) not null,
    primary key (id)
);

create table gender
(
    id         bigint generated by default as identity,
    genderName varchar(200) not null,
    primary key (id)
);
