create table Flights
(
    id                bigint generated by default as identity,
    flightNumber      varchar(100) not null,
    departureDate     datetime     not null,
    origin            varchar(200) not null,
    destination       varchar(200) not null,
    estFlightDuration integer      not null,
    maxNumSeats       integer      not null,
    primary key (id)
);

create table Passengers
(
    id           bigint generated by default as identity,
    firstName    varchar(200) not null,
    lastName     varchar(200) not null,
    passportData varchar(200) not null,
    birthDate    date         not null,
    gender       varchar(100) not null,

    primary key (id)
);

create table gender
(
    id         bigint generated by default as identity,
    genderName varchar(200) not null,
    primary key (id)
);

create table Users
(
    id        bigint generated by default as identity,
    username varchar_ignorecase(50) not null,
    password varchar_ignorecase(500) not null,
    firstName varchar(200) not null,
    lastName  varchar(200) not null,
    birthDate date         not null,
    gender    varchar(100) not null,
    primary key (username)
);

create table authorities
(
    username varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    constraint fk_authorities_users foreign key (username) references users (username)
);
create unique index ix_auth_username on authorities (username, authority);
